name: Check Plugin Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ "release/**", "develop" ]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Check Plugin Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build Plugin
        run: go build -o wait
