name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build Plugin
        run: go build -mod=mod -buildmode=plugin -o wait.so plugin.go

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          artifacts: wait.so
          skipIfReleaseExists: true
          generateReleaseNotes: true
          token: ${{ secrets.ACCESS_TOKEN }}
